server:
  # 当前Eureka Server服务端口
  port: 8761
spring:
  application:
    name: eurekaserver
  # 数据源配置
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
    #mysql5.X版本驱动包指定新的驱动类,如果是mysql8.X版本，就指定为com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver
    #   数据源其他配置, 在 DruidConfig配置类中手动绑定
    initialSize: 8
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
mybatis-plus:
  type-aliases-package: com.yckj.entity
  # xxxMapper.xml 路径
  mapper-locations: classpath*:com/yckj/mapper/**/*.xml
eureka:
  client:
    # 是否将当前的Eureka Server服务作为客户端进行注册
    register-with-eureka: false
    # 是否获取其他Eureka Server服务的数据
    fetch-registry: false
    service-url:
       # 注册中心的访问地址
      defaultZone: http://localhost:8761/eureka/
